# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db056369c9ba64bbe42382aa0d31fade8277314716dc2f5a153fedd977f6c4fc03be87ff0e299c3b9b26abf40b8b0a68db336eb0daf1f308e359615d08475f2

test:
  secret_key_base: 57c0ccce9ae0bc9569d11ffe9033abe7080ff642d062cb50a49cf551b361d26f00c04afadf23fe95efa64f657832af4b2b1055cf2cc3eaa02b955672e2f92c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
